remote_theme: pages-themes/cayman@v0.2.0
title: CsUnity
description: Counter-Strike 2 map viewer on Unity engine
plugins:
- jekyll-remote-theme
show_downloads: true
github:
  zip_url: https://github.com/in0finite/CsUnityWww/releases/download/v1.3/CsUnity-1.3-windows.zip
download_button_text: Download v1.3 for Windows
