remote_theme: pages-themes/cayman@v0.2.0
title: CsUnity
description: Counter-Strike 2 map viewer on Unity engine
plugins:
- jekyll-remote-theme
show_downloads: true
github:
  zip_url: http://example.com/download.zip
  is_project_page: false
